#!/bin/bash
# rpm-init-root: Initialize a normal-user RPM build tree

RPMMACROS="$HOME/.rpmmacros"

touch $RPMMACROS

echo "%_topdir %(echo \$HOME)/rpmbuild" >> $RPMMACROS
#echo "%_smp_mflags -j4" >> $RPMMACROS

mkdir -p `rpm --eval "%{_rpmdir}"`
mkdir -p `rpm --eval "%{_sourcedir}"`
mkdir -p `rpm --eval "%{_specdir}"`
mkdir -p `rpm --eval "%{_srcrpmdir}"`
mkdir -p `rpm --eval "%{_builddir}"`
